<?php

namespace Example\UserRegistrationBundle\Domain\Data\Repository;

use Doctrine\ORM\EntityRepository;
use Example\UserRegistrationBundle\Domain\Data\User;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{
    /**
     * @param User $user
     */
    public function add(User $user)
    {
        $this->getEntityManager()->persist($user);
    }
}
